name: 'Terraform Plan and Apply'

on:
  workflow_run:
    workflows: ['Terraform Test']
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: 'Plan Terraform Job'
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Azure login
      uses: azure/login@v2
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Generate Plan
      run: terraform plan -out=terraform.plan

    - name: Save Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform.plan

  terraform-apply:
    name: 'Apply Terraform Job'
    runs-on: ubuntu-latest
    needs: [terraform-plan]
          
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Download Plan Artifact
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan # Name of the artifact to download

    - name: Terraform Apply
      run: terraform apply -auto-approve terraform.plan